In [2]:
import numpy as np
np.random.seed(3)
n=np.random.randint(0,50,10)


In [3]:
print(n)

[42 24  3  8  0 21 19 10 43 41]


In [4]:
print(np.__version__)

1.21.5


In [5]:
arr=np.array([1,2,5,3,4])  # list as Array

In [6]:
arr

array([1, 2, 5, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr1=np.array((11,21,15,13,14))  # tuple as array
arr1

array([11, 21, 15, 13, 14])

In [9]:
# 0 D Array
arr0=np.array(23)
print("0 d array is :",arr0)
print(" Dimension is :",arr0.ndim)
# 1 D Array
arr1=np.array([22,21,23])
print("\n1 d array is :",arr1)
print(" Dimension is :",arr1.ndim)

# 2 D Array
arr2=np.array([[1,2,3],[45,56,78]])
print("\n2 d array is :",arr2)
print(" Dimension is :",arr2.ndim)
#3 D Array
arr3=np.array([[[1,2,3],[23,5,6]],[[4,5,6],[45,56,78]]])
print("\n3 d array is :",arr3)
print(" Dimension is :",arr3.ndim)

0 d array is : 23
 Dimension is : 0

1 d array is : [22 21 23]
 Dimension is : 1

2 d array is : [[ 1  2  3]
 [45 56 78]]
 Dimension is : 2

3 d array is : [[[ 1  2  3]
  [23  5  6]]

 [[ 4  5  6]
  [45 56 78]]]
 Dimension is : 3


In [10]:
#Accessing an array element
print(arr3[1][1])



vec_r=np.array([1,2,3,4,5,6])
print(vec_r)

# an col array
vec_c=np.array([[1],[2],[3],[4],[5]])
print(vec_c)
print(vec_c.ndim)

# Extracting elements from array
print(vec_r[3])
print(vec_r[:])
print(vec_r[:3])
print(vec_r[3:])


print(vec_r[-1])

[45 56 78]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]]
2
4
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [11]:
# matrix in numpy
mat=np.array([[1,2,3,4,5],[5,6,7,8,9],[7,8,9,12,11]])
print(mat)
print(mat.ndim)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 7  8  9 12 11]]
2


In [12]:
print(mat.dtype)
print(mat.shape)

int32
(3, 5)


In [13]:
print(mat.size)

#Reshapes the Matrix in new dimensions
print(mat.reshape(5,3))

#transpose
print(mat.T)

15
[[ 1  2  3]
 [ 4  5  5]
 [ 6  7  8]
 [ 9  7  8]
 [ 9 12 11]]
[[ 1  5  7]
 [ 2  6  8]
 [ 3  7  9]
 [ 4  8 12]
 [ 5  9 11]]


In [14]:
# Statical functions in numpy
print(np.max(mat))
print(np.min(mat))


print(np.max(mat, axis=0))

print(np.min(mat,axis=0))

12
1
[ 7  8  9 12 11]
[1 2 3 4 5]


In [15]:
print(np.max(mat, axis=1))

print(np.min(mat,axis=1))

[ 5  9 12]
[1 5 7]


In [16]:
print(np.mean(mat))

6.466666666666667


In [17]:
print(np.var(mat))

print(np.std(mat))
print(np.sqrt(mat))

import numpy as np
B=[True,2,3.8,np.nan,"false"]
[type(i) for i in B]


9.448888888888888
3.0739045022396008
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [2.64575131 2.82842712 3.         3.46410162 3.31662479]]


[bool, int, float, float, str]

In [18]:
import pandas as pd
pd.Series()

C:\Users\DELL\AppData\Local\Temp\ipykernel_6760\2473821312.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()


Series([], dtype: float64)

In [19]:
lst=[['anuj','aditya','Reena','Smita'],[2,3,4,5,]]
plst=pd.DataFrame(lst)
print(plst)

      0       1      2      3
0  anuj  aditya  Reena  Smita
1     2       3      4      5


In [27]:
# assinging row and column index
lst2=['anuj','aditya','Reena','Smita']
plst2=pd.DataFrame(lst2,columns=['name'])
print(plst2)

     name
0    anuj
1  aditya
2   Reena
3   Smita


In [28]:
#creating daframe from multidimentional list

mlst=[['Anil',23],['Nisha',24],['ankit',21],['vinit',34]]
plst3=pd.DataFrame(mlst,columns=['name', 'age'])
print(plst3)

    name  age
0   Anil   23
1  Nisha   24
2  ankit   21
3  vinit   34


In [29]:
#creating daframe from tuple
mlst=[('Anil',23),('Nisha',24),('ankit',21),('vinit',34)]
plst4=pd.DataFrame(mlst,columns=['name', 'age'])
print(plst4)

    name  age
0   Anil   23
1  Nisha   24
2  ankit   21
3  vinit   34


In [30]:
#creating daframe from Dictionary
mdlst={'sno':[11,12,31],'rollno':[234,345,567],'name':['anuj','Neha','Anil'],'age':[23,16,34]}
plst4=pd.DataFrame(mdlst,columns=['sno','rollno','name', 'age'])
print(plst4)

   sno  rollno  name  age
0   11     234  anuj   23
1   12     345  Neha   16
2   31     567  Anil   34


In [31]:
rollno=[2356,4567,6789]
student=['Ansh','Kapil','Meena']
class1=['Iyear', 'II year','Iyear']
dic={'s1':rollno,'s2':student,'s3':class1}
pd5=pd.DataFrame(dic,index=['a','b','c'])
pd5

s1     s2       s3
a  2356   Ansh    Iyear
b  4567  Kapil  II year
c  6789  Meena    Iyear

In [32]:

pd5.loc['a':'b','s1':'s2']

s1     s2
a  2356   Ansh
b  4567  Kapil

In [33]:
import pandas as pd
df=pd.read_csv("flavors_of_cocoa.csv")

In [34]:
df.head()

Id   Company  Bean Origin  Review Date Cocoa Percent Company Location  \
0   1  A. Morin  Agua Grande       2016.0           63%           France   
1   2  A. Morin        Kpime       2015.0           70%           France   
2   3  A. Morin       Atsane       2015.0           70%           France   
3   4  A. Morin        Akata       2015.0           70%           France   
4   5  A. Morin       Quilla       2015.0           70%           France   

   Rating  
0    3.75  
1    2.75  
2    3.00  
3    3.50  
4    3.50

In [35]:
df1=df[['Company']]
df1

Company
0     A. Morin
1     A. Morin
2     A. Morin
3     A. Morin
4     A. Morin
...        ...
1790    Zotter
1791    Zotter
1792    Zotter
1793    Zotter
1794    Zotter

[1795 rows x 1 columns]

In [36]:

# values for numeric data
df.describe()

Id  Review Date       Rating
count  1795.000000  1791.000000  1795.000000
mean    898.000000  2012.321608     3.185933
std     518.316184     2.928835     0.478062
min       1.000000  2006.000000     1.000000
25%     449.500000  2010.000000     2.875000
50%     898.000000  2013.000000     3.250000
75%    1346.500000  2015.000000     3.500000
max    1795.000000  2017.000000     5.000000

In [37]:
# class distribution
print(df.groupby('Company Location').size())

Company Location
Amsterdam              4
Argentina              9
Australia             49
Austria               26
Belgium               40
Bolivia                2
Brazil                17
Canada               125
Chile                  2
Colombia              23
Costa Rica             9
Czech Republic         1
Denmark               15
Domincan Republic      5
Ecuador               54
Eucador                1
Fiji                   4
Finland                2
France               156
Germany               35
Ghana                  1
Grenada                3
Guatemala             10
Honduras               6
Hungary               22
Iceland                3
India                  1
Ireland                4
Israel                 9
Italy                 63
Japan                 17
Lithuania              6
Madagascar            17
Martinique             1
Mexico                 4
Netherlands            4
New Zealand           17
Niacragua              1
Nicaragua              5
Peru    

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                1795 non-null   int64  
 1   Company           1795 non-null   object 
 2   Bean Origin       1795 non-null   object 
 3   Review Date       1791 non-null   float64
 4   Cocoa Percent     1795 non-null   object 
 5   Company Location  1795 non-null   object 
 6   Rating            1795 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 98.3+ KB


In [39]:
df['Rating'].max()

5.0

In [40]:
df.shape

(1795, 7)

In [41]:
df.tail()

Id Company         Bean Origin  Review Date Cocoa Percent  \
1790  1791  Zotter                Peru       2011.0           70%   
1791  1792  Zotter               Congo       2011.0           65%   
1792  1793  Zotter        Kerala State       2011.0           65%   
1793  1794  Zotter        Kerala State       2011.0           62%   
1794  1795  Zotter  Brazil, Mitzi Blue       2010.0           65%   

     Company Location  Rating  
1790          Austria    3.75  
1791          Austria    3.00  
1792          Austria    3.50  
1793          Austria    3.25  
1794          Austria    3.00

In [42]:
type(df['Rating'])

pandas.core.series.Series

In [43]:
df.index

RangeIndex(start=0, stop=1795, step=1)

In [44]:
df.set_index('Id',inplace=True)

In [45]:
df.head()

Company  Bean Origin  Review Date Cocoa Percent Company Location  Rating
Id                                                                           
1   A. Morin  Agua Grande       2016.0           63%           France    3.75
2   A. Morin        Kpime       2015.0           70%           France    2.75
3   A. Morin       Atsane       2015.0           70%           France    3.00
4   A. Morin        Akata       2015.0           70%           France    3.50
5   A. Morin       Quilla       2015.0           70%           France    3.50

In [46]:
df.loc[:,'Cocoa Percent']

Id
1       63%
2       70%
3       70%
4       70%
5       70%
       ... 
1791    70%
1792    65%
1793    65%
1794    62%
1795    65%
Name: Cocoa Percent, Length: 1795, dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1795 entries, 1 to 1795
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Company           1795 non-null   object 
 1   Bean Origin       1795 non-null   object 
 2   Review Date       1791 non-null   float64
 3   Cocoa Percent     1795 non-null   object 
 4   Company Location  1795 non-null   object 
 5   Rating            1795 non-null   float64
dtypes: float64(2), object(4)
memory usage: 98.2+ KB


In [51]:
df.isnull()

Company  Bean Origin  Review Date  Cocoa Percent  Company Location  \
Id                                                                         
1       False        False        False          False             False   
2       False        False        False          False             False   
3       False        False        False          False             False   
4       False        False        False          False             False   
5       False        False        False          False             False   
...       ...          ...          ...            ...               ...   
1791    False        False        False          False             False   
1792    False        False        False          False             False   
1793    False        False        False          False             False   
1794    False        False        False          False             False   
1795    False        False        False          False             False   

      Rating  
Id            
1      False  
2      False  
3      False  
4      False  
5      False  
...      ...  
1791   False  
1792   False  
1793   False  
1794   False  
1795   False  

[1795 rows x 6 columns]

In [52]:
np.unique(df['Rating'])

array([1.  , 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75,
       4.  , 5.  ])

In [53]:
df.dtypes

Company              object
Bean Origin          object
Review Date         float64
Cocoa Percent        object
Company Location     object
Rating              float64
dtype: object

In [54]:
temo_df=df.append(df)

In [55]:
temo_df.shape


(3590, 6)

In [57]:
temo_df=temo_df.drop_duplicates()

In [58]:
temo_df.shape


(1795, 6)

In [63]:
df['Company'].describe()

count     1795
unique     416
top       Soma
freq        47
Name: Company, dtype: object

In [65]:
df['Company Location'].describe()

count       1795
unique        60
top       U.S.A.
freq         764
Name: Company Location, dtype: object

In [66]:
import pandas as pd
data = [1,2,3,10,20,30]
df = pd.DataFrame(data)
print(df)


    0
0   1
1   2
2   3
3  10
4  20
5  30


In [67]:
import pandas as pd
data = {'Name' : ['AA', 'BB'], 'Age': [30,45]}
df = pd.DataFrame(data)
print(df)


  Name  Age
0   AA   30
1   BB   45


In [68]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df)


   a   b     c
0  1   2   NaN
1  5  10  20.0


In [69]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
print(df)


        a   b     c
first   1   2   NaN
second  5  10  20.0


In [70]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]

#With two column indices, values same as dictionary keys
df1 = pd.DataFrame(data,index=['first','second'],columns=['a','b'])

#With two column indices with one index with other name
df2 = pd.DataFrame(data,index=['first','second'],columns=['a','b1'])

print(df1)
print('...........')
print(df2)


        a   b
first   1   2
second  5  10
...........
        a  b1
first   1 NaN
second  5 NaN


In [71]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3]  , index=['a', 'b', 'c']), 
     'two' : pd.Series([1,2, 3, 4], index=['a', 'b', 'c', 'd'])
    }
df = pd.DataFrame(d)
print(df)


   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [72]:
import pandas as pd
d = {'one':pd.Series([1,2,3],   index=['a','b','c']), 
     'two':pd.Series([1,2,3,4], index=['a','b','c','d'])
    }
df = pd.DataFrame(d)
# Adding a new column to an existing DataFrame object
# with column label by passing new series

print("Adding a new column by passing as Series:")
df['three'] = pd.Series([10,20,30],index=['a','b','c'])
print(df)

print("Adding a column using an existing columns in DataFrame:")
df['four'] = df['one']+df['three']
print(df)


Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adding a column using an existing columns in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


In [73]:
import pandas as pd
d = {'one':pd.Series([1, 2, 3],    index=['a','b','c']),
     'two':pd.Series([1, 2, 3, 4], index=['a','b','c','d'])
    }
df = pd.DataFrame(d)
print(df)

df2 = pd.DataFrame([[5,6], [7,8]], columns = ['a', 'b'])
df = df.append(df2 )
print(df)

df = df.drop(0)
print(df)


   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
   one  two    a    b
a  1.0  1.0  NaN  NaN
b  2.0  2.0  NaN  NaN
c  3.0  3.0  NaN  NaN
d  NaN  4.0  NaN  NaN
0  NaN  NaN  5.0  6.0
1  NaN  NaN  7.0  8.0
   one  two    a    b
a  1.0  1.0  NaN  NaN
b  2.0  2.0  NaN  NaN
c  3.0  3.0  NaN  NaN
d  NaN  4.0  NaN  NaN
1  NaN  NaN  7.0  8.0


In [74]:
import pandas as pd
# Creating the first dataframe
df1 = pd.DataFrame({"A":[1, 5, 3, 4, 2], "B":[3, 2, 4, 3, 4], "C":[2, 2, 7, 3, 4],"D":[4, 3, 6, 12, 7]},
		     index =["A1", "A2", "A3", "A4", "A5"])

# Creating the second dataframe
df2 = pd.DataFrame({"A":[10, 11, 7, 8, 5],
		     "B":[21, 5, 32, 4, 6],
		     "C":[11, 21, 23, 7, 9],
		     "D":[1, 5, 3, 8, 6]},
		     index =["A1", "A3", "A4", "A7", "A8"])

# Print the first dataframe
print(df1)
print(df2)
# find matching indexes
df1.reindex_like(df2)


    A  B  C   D
A1  1  3  2   4
A2  5  2  2   3
A3  3  4  7   6
A4  4  3  3  12
A5  2  4  4   7
     A   B   C  D
A1  10  21  11  1
A3  11   5  21  5
A4   7  32  23  3
A7   8   4   7  8
A8   5   6   9  6


A    B    C     D
A1  1.0  3.0  2.0   4.0
A3  3.0  4.0  7.0   6.0
A4  4.0  3.0  3.0  12.0
A7  NaN  NaN  NaN   NaN
A8  NaN  NaN  NaN   NaN

In [75]:
import pandas as pd
df1 = pd.DataFrame({'Name':['A','B'], 'SSN':[10,20], 'marks':[90, 95] })
df2 = pd.DataFrame({'Name':['B','C'], 'SSN':[25,30], 'marks':[80, 97] })
df3 = pd.concat([df1, df2])
df3


Name  SSN  marks
0    A   10     90
1    B   20     95
0    B   25     80
1    C   30     97

In [76]:
import pandas as pd
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c'])
print(cat)


['a', 'b', 'c', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']


In [81]:
import pandas as pd
import numpy as np
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
print("cat is :",cat)
df = pd.DataFrame({"cat": cat, "s":["a", "c", "c", np.nan]})
print("\n Dataframe df is :\n",df)
print("\n describtion of df:\n", df.describe())
print("\n describtion of only column cat is:\n", df["cat"].describe())


cat is : ['a', 'c', 'c', NaN]
Categories (3, object): ['b', 'a', 'c']

 Dataframe df is :
    cat    s
0    a    a
1    c    c
2    c    c
3  NaN  NaN

 describtion of df:
        cat  s
count    3  3
unique   2  2
top      c  c
freq     2  2

 describtion od only column cat is:
 count     3
unique    2
top       c
freq      2
Name: cat, dtype: object
