In [4]:
import numpy as np
np.random.seed(3)
n=np.random.randint(0,50,10)


In [5]:
print(n)

[42 24  3  8  0 21 19 10 43 41]


In [6]:
print(np.__version__)

1.21.5


In [7]:
arr=np.array([1,2,5,3,4])  # list as Array

In [ ]:
arr

In [9]:
type(arr)

numpy.ndarray

In [11]:
arr1=np.array((11,21,15,13,14))  # tuple as array
arr1

array([11, 21, 15, 13, 14])

In [31]:
# 0 D Array
arr0=np.array(23)
print("0 d array is :",arr0)
print(" Dimension is :",arr0.ndim)
# 1 D Array
arr1=np.array([22,21,23])
print("\n1 d array is :",arr1)
print(" Dimension is :",arr1.ndim)

# 2 D Array
arr2=np.array([[1,2,3],[45,56,78]])
print("\n2 d array is :",arr2)
print(" Dimension is :",arr2.ndim)
#3 D Array
arr3=np.array([[[1,2,3],[23,5,6]],[[4,5,6],[45,56,78]]])
print("\n3 d array is :",arr3)
print(" Dimension is :",arr3.ndim)

0 d array is : 23
 Dimension is : 0

1 d array is : [22 21 23]
 Dimension is : 1

2 d array is : [[ 1  2  3]
 [45 56 78]]
 Dimension is : 2

3 d array is : [[[ 1  2  3]
  [23  5  6]]

 [[ 4  5  6]
  [45 56 78]]]
 Dimension is : 3


In [49]:
#Accessing an array element
print(arr3[1][1])

vec_r=np.array([1,2,3,4,5,6])
print(vec_r)

# an col array
vec_c=np.array([[1],[2],[3],[4],[5]])
print(vec_c)
print(vec_c.ndim)

# Extracting elements from array
print(vec_r[3])
print(vec_r[:])
print(vec_r[:3])
print(vec_r[3:])


print(vec_r[-1])

[45 56 78]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]]
2
4
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [52]:
# matrix in numpy
mat=np.array([[1,2,3,4,5],[5,6,7,8,9],[7,8,9,12,11]])
print(mat)
print(mat.ndim)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 7  8  9 12 11]]
2


In [54]:
print(mat.dtype)
print(mat.shape)

int32
(3, 5)


In [58]:
print(mat.size)

#Reshapes the Matrix in new dimensions
print(mat.reshape(5,3))

#transpose
print(mat.T)

15
[[ 1  2  3]
 [ 4  5  5]
 [ 6  7  8]
 [ 9  7  8]
 [ 9 12 11]]
[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 7  8  9 12 11]]
[[ 1  5  7]
 [ 2  6  8]
 [ 3  7  9]
 [ 4  8 12]
 [ 5  9 11]]


In [62]:
# Statical functions in numpy
print(np.max(mat))
print(np.min(mat))


print(np.max(mat, axis=0))

print(np.min(mat,axis=0))

12
1
[ 7  8  9 12 11]
[1 2 3 4 5]


In [63]:
print(np.max(mat, axis=1))

print(np.min(mat,axis=1))

[ 5  9 12]
[1 5 7]


In [64]:
print(np.mean(mat))

6.466666666666667


In [67]:
print(np.var(mat))

print(np.std(mat))
print(np.sqrt(mat))




9.448888888888888
3.0739045022396008
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [2.64575131 2.82842712 3.         3.46410162 3.31662479]]


AttributeError: module 'numpy' has no attribute 'sqr'